// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOB-mD2zK0FtzNrorUbIM9S_qMlt4eQ3U',
    appId: '1:851136390775:web:655733ee93a52581ea8872',
    messagingSenderId: '851136390775',
    projectId: 'giftcard-wallet-21003',
    authDomain: 'giftcard-wallet-21003.firebaseapp.com',
    storageBucket: 'giftcard-wallet-21003.firebasestorage.app',
    measurementId: 'G-JB1TQBD276',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUqfnv4znPU5asERjc8NPnH20mjeitGA',
    appId: '1:851136390775:android:ef5fac74b9698a13ea8872',
    messagingSenderId: '851136390775',
    projectId: 'giftcard-wallet-21003',
    storageBucket: 'giftcard-wallet-21003.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocshVzBFRQ53DxxG1kEy5eNMyMZofUWc',
    appId: '1:851136390775:ios:f230807e34bb05adea8872',
    messagingSenderId: '851136390775',
    projectId: 'giftcard-wallet-21003',
    storageBucket: 'giftcard-wallet-21003.firebasestorage.app',
    iosBundleId: 'com.example.giftcardWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCocshVzBFRQ53DxxG1kEy5eNMyMZofUWc',
    appId: '1:851136390775:ios:f230807e34bb05adea8872',
    messagingSenderId: '851136390775',
    projectId: 'giftcard-wallet-21003',
    storageBucket: 'giftcard-wallet-21003.firebasestorage.app',
    iosBundleId: 'com.example.giftcardWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOB-mD2zK0FtzNrorUbIM9S_qMlt4eQ3U',
    appId: '1:851136390775:web:673b375adc96c46dea8872',
    messagingSenderId: '851136390775',
    projectId: 'giftcard-wallet-21003',
    authDomain: 'giftcard-wallet-21003.firebaseapp.com',
    storageBucket: 'giftcard-wallet-21003.firebasestorage.app',
    measurementId: 'G-89JLL98NXK',
  );
}
